#!/bin/sh

for i in 0 1 2 3 4 ; do \
  docker kill cdk-data-availability-$$i || true
  docker rm cdk-data-availability-$$i || true
  docker kill cdk-validium-data-node-db-$$i || true
  docker rm cdk-validium-data-node-db-$$i || true
done

