with-expecter: true
dir: "mocks"
filename: "{{.InterfaceName | lower }}.generated.go"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/ethereum/go-ethereum/event:
    config:
    interfaces:
      Subscription:
        config:
  github.com/0xPolygon/cdk-data-availability/db:
    config:
    interfaces:
      DB:
        config:
      Tx:
        config:
  github.com/0xPolygon/cdk-data-availability/client:
    config:
    interfaces:
      ClientFactory:
        config:
      Client:
        config:
  github.com/0xPolygon/cdk-data-availability/etherman:
    config:
    interfaces:
      Etherman:
        config:
  github.com/0xPolygon/cdk-data-availability/sequencer:
    config:
    interfaces:
      ISequencerTracker:
        config:
          filename: sequencer_tracker.generated.go
  github.com/0xPolygon/cdk-data-availability/types:
    config:
    interfaces:
      IEthClient:
        config:
          filename: eth_client.generated.go
      IEthClientFactory:
        config:
          filename: eth_client_factory.generated.go