name: Lint
on:
  push:
    branches:
      - main
      - master
      - develop
      - update-external-dependencies
      - 'release/**'
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lint
        run: |
          make generate
          make install-linter
          make lint
