name: Regression Tests

on:
  pull_request:
    types: [opened, synchronize]  # Trigger on new PR and existing with new commits
    branches:
      - main

jobs:
  deploy_devnet:
    strategy: 
      matrix:
        go-version: [ 1.22.x ]
        goarch: [ "amd64" ]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
        env:
          GOARCH: ${{ matrix.goarch }}

      - name: Checkout cdk-data-availability
        uses: actions/checkout@v4
        with:
          path: cdk-data-availability

      - name: Checkout kurtosis-cdk
        uses: actions/checkout@v4
        with:
          repository: 0xPolygon/kurtosis-cdk
          ref: "v0.2.15"
          path: kurtosis-cdk

      # - name: Install Kurtosis CDK tools
      #   uses: ./kurtosis-cdk/.github/actions/setup-kurtosis-cdk

      - name: Install kurtosis
        shell: bash
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli=1.3.0
          kurtosis version
  
      - name: Disable kurtosis analytics
        shell: bash
        run: kurtosis analytics disable
  
      - name: Install yq
        shell: bash
        run: |
          pip3 install yq
          yq --version

      - name: Build docker image
        working-directory: ./cdk-data-availability
        run: docker build -t cdk-data-availability:local --file Dockerfile .

      # - name: Configure Kurtosis CDK
      #   working-directory: ./kurtosis-cdk
      #   run: |
      #     yq -Y --in-place '.args.data_availability_mode = "cdk-validium"' params.yml
      #     yq -Y --in-place '.args.zkevm_da_image = "cdk-data-availability:local"' params.yml

      # - name: Deploy Kurtosis CDK package
      #   working-directory: ./kurtosis-cdk
      #   run: kurtosis run --enclace cdk . '{"args": {"zkevm_da_image": "cdk-data-availability:local"}}'

      - name: Deploy Kurtosis CDK package
        working-directory: ./kurtosis-cdk
        run: >
          kurtosis run --enclave cdk . '{"args": {"zkevm_da_image": "cdk-data-availability:local"}}'

      - name: Set executable permissions for the script
        working-directory: ./cdk-data-availability
        run: sudo chmod +x .github/actions/monitor-cdk-verified-batches/batch_verification_monitor.sh

      - name: Monitor verified batches
        working-directory: ./cdk-data-availability
        shell: bash
        run: .github/actions/monitor-cdk-verified-batches/batch_verification_monitor.sh 19 600