name: Regression Tests

on:
  pull_request:
    types: [opened, synchronize]  # Trigger on new PR and existing with new commits
    branches:
      - main

jobs:
  deploy_devnet:
    strategy: 
      matrix:
        go-version: [ 1.22.x ]
        goarch: [ "amd64" ]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
        env:
          GOARCH: ${{ matrix.goarch }}

      - name: Checkout cdk-data-availability
        uses: actions/checkout@v4
        with:
          path: cdk-data-availability

      - name: Checkout kurtosis-cdk
        uses: actions/checkout@v4
        with:
          repository: 0xPolygon/kurtosis-cdk
          ref: v0.2.24
          path: kurtosis-cdk

      - name: Install Kurtosis CDK tools
        uses: ./kurtosis-cdk/.github/actions/setup-kurtosis-cdk

      - name: Build docker image
        working-directory: ./cdk-data-availability
        run: docker build -t cdk-data-availability:local --file Dockerfile .

      - name: Deploy Kurtosis CDK package
        working-directory: ./kurtosis-cdk
        run: >
          kurtosis run --enclave cdk . '{"args": {"zkevm_da_image": "cdk-data-availability:local", "consensus_contract_type": "cdk-validium"}}'

      - name: Set executable permissions for the script
        working-directory: ./kurtosis-cdk
        run: sudo chmod +x .github/scripts/monitor-verified-batches.sh

      - name: Monitor verified batches
        working-directory: ./kurtosis-cdk
        shell: bash
        run: |
          rpc_url="$(kurtosis port print cdk cdk-erigon-rpc-001 rpc)"
          echo "Using RPC URL: $rpc_url"
          .github/scripts/monitor-verified-batches.sh --enclave cdk --rpc-url "$rpc_url" --target 19 --timeout 600