---
name: Test e2e
on:
  push:
    branches:
      - main
      - master
      - develop
      - update-external-dependencies
      - 'release/**'
  pull_request:

jobs:
  test-e2e:
    strategy:
      fail-fast: false
      matrix:
        go-version: [ 1.19.x ]
        goarch: [ "amd64" ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
      env:
        GOARCH: ${{ matrix.goarch }}

    - name: Build Docker
      run: make build-docker

    - name: Test
      run: make test-e2e
      working-directory: test
